### ISSUE TITLE
登陆失败'msg': '参数不合法', 'code': '-1', 'detailCode': '-2'

### ISSUE THREAD

**Issue by GarfieldF** [WeiYuanStudio/AutoWeiBan#2]

**Comment by WeiYuanStudio** [comment]
您好，很高兴收到了您的Issues，感谢您对本项目的支持！
很抱歉我现在才回复，我忘记开启本仓库的watch，这导致我无法接收到任何通知

经过我的检查，现在很抱歉的通知您，**他们的登录界面修改了提交的方式**。**登录POST请求“login.do”中的登录信息被重新编码了**，所以也就**无法登录**了。

由于不是开学季，被使用频率不高，个人的力量干不过官方团队的封杀速度。更新意义不大。而且学业繁忙。该项目暂停维护，对此表示十分抱歉，还望理解。

**当然备选方案也是有的**。
我的学弟用JS开发了一个刷课脚本，您可以尝试一下
详情访问：
学弟的WBKiller脚本的git仓库地址
<https://git.darc.pro/DarcJC/WBKiller>
使用方法链接位于学弟的个人博客
<https://darc.pro/archives/wbcourse-killer.html>

**Comment by WeiYuanStudio** [comment]
您好，目前已经更新至版本 92898ced 紧急修复了您所说的上述问题。本人也已经经过登录测试。欢迎测试使用
发现这次官方更新主要改动了一下内容：

- 登录POST请求混淆了账号密码，不再是明文登录。未知是否针对该项目，目前通过二维码登录解决
- 请求课程数量的返回JSON改变了大量键值，目前也已经解决了

不知道在完成课程请求方面是否有改动，这得靠新号测试才能知道。后期将加入更多的log输出方便用户反馈
若还有其他疑问欢迎继续提交新的Issues。十分感谢您的反馈
