### ISSUE TITLE
weiban.py 似乎少了句 import requests ?

### ISSUE THREAD

**Issue by artiga033** [WeiYuanStudio/AutoWeiBan#4]
首先十分感谢本项目

clone后运行发现 `weiban.py` 中没有引入requests 但是line 41 和 line 177 都用了`requests.get`。
加上`import requests`后运行 一切正常

翻了下commit history发现之前是有这句的， 所以其实是想取消对requests的依赖但漏了这两行？还是遗漏了这句import?

**Comment by WeiYuanStudio** [comment]
感谢您的反馈，确实是漏了这个。稍后加回去
